//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int IdActor { get; set; }
        public string Codigo { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombres { get; set; }
        public string NombreCorto { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> IdTenor { get; set; }
        public Nullable<bool> Genero { get; set; }
        public Nullable<int> IdCivil { get; set; }
        public Nullable<int> NumeroHijo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> IdPaisNacimiento { get; set; }
        public string IdUbigeoNacimiento { get; set; }
        public string OtroNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Urbanizacion { get; set; }
        public string DireccionReferencia { get; set; }
        public Nullable<int> IdPais { get; set; }
        public string IdUbigeo { get; set; }
        public string OtraCiudad { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string TelefonoReferencial { get; set; }
        public string Celular { get; set; }
        public Nullable<int> IdMovil { get; set; }
        public Nullable<int> IdProcedencia { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Ruc { get; set; }
        public string EMail { get; set; }
        public string EMailOpcional { get; set; }
        public string EMailAdicional { get; set; }
        public Nullable<bool> Trabaja { get; set; }
        public string CurriculoNombre { get; set; }
        public Nullable<bool> OkIdUsuario { get; set; }
        public Nullable<System.DateTime> OKFecha { get; set; }
        public Nullable<int> IdFamilia { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdCounter { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string CodigoAnterior { get; set; }
        public string Codigocarnet { get; set; }
        public string PedidoER3Carnet { get; set; }
        public string ReqMatricula { get; set; }
        public string GeneroClave { get; set; }
        public Nullable<bool> EsEditadoPorUsuario { get; set; }
        public Nullable<int> IdCalificacion { get; set; }
        public string AreaInteres { get; set; }
        public string CV { get; set; }
        public string NumeroPasaporte { get; set; }
        public Nullable<bool> EsAnulado { get; set; }
        public Nullable<bool> EsAnuladoParcial { get; set; }
        public string Token { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string AreaInvestigacion { get; set; }
    }
}
