//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionMedicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionMedicion()
        {
            this.EvaluacionPromocionMedicion = new HashSet<EvaluacionPromocionMedicion>();
            this.EvaluacionPromocionParticipante = new HashSet<EvaluacionPromocionParticipante>();
            this.EvaluacionRespuesta = new HashSet<EvaluacionRespuesta>();
            this.PromocionMedicionCicloParticipante = new HashSet<PromocionMedicionCicloParticipante>();
        }
    
        public int EvaluacionMedicionID { get; set; }
        public long EvaluacionCicloID { get; set; }
        public string EvaluacionMedicionDescripcion { get; set; }
        public Nullable<bool> EvaluacionMedicionEstado { get; set; }
    
        public virtual EvaluacionCiclo EvaluacionCiclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionMedicion> EvaluacionPromocionMedicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionParticipante> EvaluacionPromocionParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromocionMedicionCicloParticipante> PromocionMedicionCicloParticipante { get; set; }
    }
}
