//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionAlternativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionAlternativa()
        {
            this.EvaluacionRespuesta = new HashSet<EvaluacionRespuesta>();
        }
    
        public long EvaluacionAlternativaID { get; set; }
        public Nullable<long> EvaluacionPreguntaID { get; set; }
        public string EvaluacionAlternativaDescripcion { get; set; }
    
        public virtual EvaluacionPregunta EvaluacionPregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
    }
}
