//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPromocionCiclo
    {
        public int EvaluacionPromocionID { get; set; }
        public long EvaluacionCicloID { get; set; }
        public Nullable<System.DateTime> EvaluacionPromCicloFecIni { get; set; }
        public Nullable<System.DateTime> EvaluacionPromCicloFecFin { get; set; }
    
        public virtual EvaluacionCiclo EvaluacionCiclo { get; set; }
        public virtual EvaluacionPromocion EvaluacionPromocion { get; set; }
    }
}
