//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionPregunta()
        {
            this.EvaluacionAlternativa = new HashSet<EvaluacionAlternativa>();
        }
    
        public long EvaluacionPreguntaID { get; set; }
        public Nullable<long> EvaluacionNivelID { get; set; }
        public string EvaluacionPreguntaDescripcion { get; set; }
        public Nullable<bool> EsInversa { get; set; }
        public string EvaluacionPreguntaPares { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionAlternativa> EvaluacionAlternativa { get; set; }
        public virtual EvaluacionNivel EvaluacionNivel { get; set; }
    }
}
