//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionNivelIntro
    {
        public long EvaluacionNivelIntroID { get; set; }
        public long EvaluacionNivelID { get; set; }
        public string ParrafoIntroduccion1 { get; set; }
        public string ListaIntroduccion1 { get; set; }
        public string ParrafoIntroduccion2 { get; set; }
        public string ListaIntroduccion2 { get; set; }
        public string ParrafoIntroduccion3 { get; set; }
        public string ListaAlternativas { get; set; }
        public string ParrafoIntroduccionPar1 { get; set; }
        public string ListaIntroduccionPar1 { get; set; }
        public string ParrafoIntroduccionPar2 { get; set; }
        public string ListaIntroduccionPar2 { get; set; }
        public string ParrafoIntroduccionPar3 { get; set; }
    
        public virtual EvaluacionNivel EvaluacionNivel { get; set; }
    }
}
