//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPromocionMedicion
    {
        public int EvaluacionPromocionID { get; set; }
        public long EvaluacionCicloID { get; set; }
        public int EvaluacionMedicionID { get; set; }
        public Nullable<System.DateTime> EvaluacionPromMedicionFecIni { get; set; }
        public Nullable<System.DateTime> EvaluacionPromMedicionFecFin { get; set; }
        public string EvaluacionMedicionDescripcion { get; set; }
        public Nullable<bool> EsEvaluado { get; set; }
    
        public virtual EvaluacionCiclo EvaluacionCiclo { get; set; }
        public virtual EvaluacionMedicion EvaluacionMedicion { get; set; }
        public virtual EvaluacionPromocion EvaluacionPromocion { get; set; }
    }
}
