//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPromocionCiclo
    {
        public int EvaluacionPromocionID { get; set; }
        public long EvaluacionCicloID { get; set; }
        public Nullable<System.DateTime> EvaluacionPromCicloFecIni { get; set; }
        public Nullable<System.DateTime> EvaluacionPromCicloFecFin { get; set; }
        public Nullable<int> EvaluacionCicloNro { get; set; }
        public string EvaluacionCicloDescripcion { get; set; }
    
        public virtual EvaluacionCiclo EvaluacionCiclo { get; set; }
        public virtual EvaluacionPromocion EvaluacionPromocion { get; set; }
    }
}
