//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionPregunta()
        {
            this.EvaluacionAlternativa = new HashSet<EvaluacionAlternativa>();
        }
    
        public long EvaluacionPreguntaID { get; set; }
        public Nullable<long> EvaluacionNivelID { get; set; }
        public string EvaluacionPreguntaDescripcion { get; set; }
        public Nullable<bool> EsInversa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionAlternativa> EvaluacionAlternativa { get; set; }
        public virtual EvaluacionNivel EvaluacionNivel { get; set; }
    }
}
