//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionRespuesta
    {
        public int EvaluacionPromocionID { get; set; }
        public long ParticipanteID { get; set; }
        public long EvaluacionAlternativaID { get; set; }
        public int EvaluacionMedicionID { get; set; }
        public Nullable<long> ParticipanteEvaluadoID { get; set; }
    
        public virtual EvaluacionAlternativa EvaluacionAlternativa { get; set; }
        public virtual EvaluacionMedicion EvaluacionMedicion { get; set; }
        public virtual EvaluacionPromocion EvaluacionPromocion { get; set; }
        public virtual Participante Participante { get; set; }
        public virtual Participante Participante1 { get; set; }
    }
}
