//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionCiclo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionCiclo()
        {
            this.EvaluacionMedicion = new HashSet<EvaluacionMedicion>();
            this.EvaluacionPromocionCiclo = new HashSet<EvaluacionPromocionCiclo>();
            this.EvaluacionPromocionMedicion = new HashSet<EvaluacionPromocionMedicion>();
            this.PromocionMedicionCicloParticipante = new HashSet<PromocionMedicionCicloParticipante>();
        }
    
        public long EvaluacionCicloID { get; set; }
        public int EvaluacionID { get; set; }
        public int EvaluacionCicloNro { get; set; }
        public string EvaluacionCicloDescripcion { get; set; }
        public Nullable<bool> EvaluacionCicloEstado { get; set; }
    
        public virtual Evaluacion Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionMedicion> EvaluacionMedicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionCiclo> EvaluacionPromocionCiclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionMedicion> EvaluacionPromocionMedicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromocionMedicionCicloParticipante> PromocionMedicionCicloParticipante { get; set; }
    }
}
