//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionCiclo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionCiclo()
        {
            this.EvaluacionMedicion = new HashSet<EvaluacionMedicion>();
            this.EvaluacionPromocionCiclo = new HashSet<EvaluacionPromocionCiclo>();
            this.EvaluacionPromocionMedicion = new HashSet<EvaluacionPromocionMedicion>();
        }
    
        public long EvaluacionCicloID { get; set; }
        public int EvaluacionID { get; set; }
        public int EvaluacionCicloNro { get; set; }
        public string EvaluacionCicloDescripcion { get; set; }
        public Nullable<bool> EvaluacionCicloEstado { get; set; }
    
        public virtual Evaluacion Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionMedicion> EvaluacionMedicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionCiclo> EvaluacionPromocionCiclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionMedicion> EvaluacionPromocionMedicion { get; set; }
    }
}
