//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionAlternativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionAlternativa()
        {
            this.EvaluacionRespuesta = new HashSet<EvaluacionRespuesta>();
        }
    
        public long EvaluacionAlternativaID { get; set; }
        public Nullable<long> EvaluacionPreguntaID { get; set; }
        public string EvaluacionAlternativaDescripcion { get; set; }
        public Nullable<int> EvaluacionAlternativaValor { get; set; }
    
        public virtual EvaluacionPregunta EvaluacionPregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
    }
}
