//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPromocion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionPromocion()
        {
            this.EvaluacionPromocionCiclo = new HashSet<EvaluacionPromocionCiclo>();
            this.EvaluacionRespuesta = new HashSet<EvaluacionRespuesta>();
            this.EvaluacionPromocionMedicion = new HashSet<EvaluacionPromocionMedicion>();
            this.EvaluacionPromocionParticipante = new HashSet<EvaluacionPromocionParticipante>();
        }
    
        public int EvaluacionPromocionID { get; set; }
        public int EvaluacionID { get; set; }
        public string EvaluacionPromocionCodigo { get; set; }
        public string EvaluacionPromocionDescripcion { get; set; }
        public Nullable<System.DateTime> EvaluacionPromocionFecIni { get; set; }
        public Nullable<System.DateTime> EvaluacionPromocionFecFin { get; set; }
        public bool EvaluacionPromocionEstado { get; set; }
        public string EvaluacionPromocionCorreo { get; set; }
    
        public virtual Evaluacion Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionCiclo> EvaluacionPromocionCiclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionMedicion> EvaluacionPromocionMedicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionParticipante> EvaluacionPromocionParticipante { get; set; }
    }
}
