//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDEvaluacionEntities : DbContext
    {
        public BDEvaluacionEntities()
            : base("name=BDEvaluacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evaluacion> Evaluacion { get; set; }
        public virtual DbSet<EvaluacionAlternativa> EvaluacionAlternativa { get; set; }
        public virtual DbSet<EvaluacionCiclo> EvaluacionCiclo { get; set; }
        public virtual DbSet<EvaluacionMedicion> EvaluacionMedicion { get; set; }
        public virtual DbSet<EvaluacionNivel> EvaluacionNivel { get; set; }
        public virtual DbSet<EvaluacionNivelIntro> EvaluacionNivelIntro { get; set; }
        public virtual DbSet<EvaluacionParticipante> EvaluacionParticipante { get; set; }
        public virtual DbSet<EvaluacionPregunta> EvaluacionPregunta { get; set; }
        public virtual DbSet<EvaluacionPromocion> EvaluacionPromocion { get; set; }
        public virtual DbSet<EvaluacionPromocionCiclo> EvaluacionPromocionCiclo { get; set; }
        public virtual DbSet<EvaluacionPromocionMedicion> EvaluacionPromocionMedicion { get; set; }
        public virtual DbSet<EvaluacionPromocionParticipante> EvaluacionPromocionParticipante { get; set; }
        public virtual DbSet<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
        public virtual DbSet<EvaluacionUsuario> EvaluacionUsuario { get; set; }
        public virtual DbSet<Participante> Participante { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoRelacionParticipante> TipoRelacionParticipante { get; set; }
        public virtual DbSet<PromocionMedicionCicloParticipante> PromocionMedicionCicloParticipante { get; set; }
    
        public virtual ObjectResult<PromedioEvaluacionxCicloNivel_Result> PromedioEvaluacionxCicloNivel(Nullable<int> idEvaluacion, Nullable<int> idNivelPadre, Nullable<int> idPromocion, Nullable<int> idCiclo, Nullable<int> idParticipante)
        {
            var idEvaluacionParameter = idEvaluacion.HasValue ?
                new ObjectParameter("IdEvaluacion", idEvaluacion) :
                new ObjectParameter("IdEvaluacion", typeof(int));
    
            var idNivelPadreParameter = idNivelPadre.HasValue ?
                new ObjectParameter("IdNivelPadre", idNivelPadre) :
                new ObjectParameter("IdNivelPadre", typeof(int));
    
            var idPromocionParameter = idPromocion.HasValue ?
                new ObjectParameter("IdPromocion", idPromocion) :
                new ObjectParameter("IdPromocion", typeof(int));
    
            var idCicloParameter = idCiclo.HasValue ?
                new ObjectParameter("IdCiclo", idCiclo) :
                new ObjectParameter("IdCiclo", typeof(int));
    
            var idParticipanteParameter = idParticipante.HasValue ?
                new ObjectParameter("IdParticipante", idParticipante) :
                new ObjectParameter("IdParticipante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PromedioEvaluacionxCicloNivel_Result>("PromedioEvaluacionxCicloNivel", idEvaluacionParameter, idNivelPadreParameter, idPromocionParameter, idCicloParameter, idParticipanteParameter);
        }
    
        public virtual ObjectResult<sp_PromedioEvaluacion_Result> sp_PromedioEvaluacion(Nullable<int> idParticipanteEvaluar, Nullable<int> idPromocion, Nullable<int> idMedicion)
        {
            var idParticipanteEvaluarParameter = idParticipanteEvaluar.HasValue ?
                new ObjectParameter("IdParticipanteEvaluar", idParticipanteEvaluar) :
                new ObjectParameter("IdParticipanteEvaluar", typeof(int));
    
            var idPromocionParameter = idPromocion.HasValue ?
                new ObjectParameter("IdPromocion", idPromocion) :
                new ObjectParameter("IdPromocion", typeof(int));
    
            var idMedicionParameter = idMedicion.HasValue ?
                new ObjectParameter("IdMedicion", idMedicion) :
                new ObjectParameter("IdMedicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PromedioEvaluacion_Result>("sp_PromedioEvaluacion", idParticipanteEvaluarParameter, idPromocionParameter, idMedicionParameter);
        }
    }
}
