//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEvaluacionEntities : DbContext
    {
        public BDEvaluacionEntities()
            : base("name=BDEvaluacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evaluacion> Evaluacion { get; set; }
        public virtual DbSet<EvaluacionAlternativa> EvaluacionAlternativa { get; set; }
        public virtual DbSet<EvaluacionCiclo> EvaluacionCiclo { get; set; }
        public virtual DbSet<EvaluacionMedicion> EvaluacionMedicion { get; set; }
        public virtual DbSet<EvaluacionNivel> EvaluacionNivel { get; set; }
        public virtual DbSet<EvaluacionParticipante> EvaluacionParticipante { get; set; }
        public virtual DbSet<EvaluacionPregunta> EvaluacionPregunta { get; set; }
        public virtual DbSet<EvaluacionPromocion> EvaluacionPromocion { get; set; }
        public virtual DbSet<EvaluacionPromocionCiclo> EvaluacionPromocionCiclo { get; set; }
        public virtual DbSet<EvaluacionPromocionMedicion> EvaluacionPromocionMedicion { get; set; }
        public virtual DbSet<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
        public virtual DbSet<Participante> Participante { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
    }
}
