//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participante()
        {
            this.EvaluacionPromocionParticipante = new HashSet<EvaluacionPromocionParticipante>();
            this.EvaluacionRespuesta = new HashSet<EvaluacionRespuesta>();
            this.EvaluacionRespuesta1 = new HashSet<EvaluacionRespuesta>();
        }
    
        public long ParticipanteID { get; set; }
        public string ParticipanteApePaterno { get; set; }
        public string ParticipanteApeMaterno { get; set; }
        public string ParticipanteNombres { get; set; }
        public string ParticipanteNombreCompleto { get; set; }
        public Nullable<int> TipoDocumentoID { get; set; }
        public string ParticipanteNroDoc { get; set; }
        public Nullable<System.DateTime> ParticipanteFecNac { get; set; }
        public string ParticipanteEmail { get; set; }
        public string ParticipanteEmailOpcional { get; set; }
        public string ParticipanteTelefono { get; set; }
        public string ParticipanteTelefonoOpcional { get; set; }
        public Nullable<bool> ParticipanteEstado { get; set; }
        public Nullable<int> TipoRelacionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionPromocionParticipante> EvaluacionPromocionParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionRespuesta> EvaluacionRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionRespuesta> EvaluacionRespuesta1 { get; set; }
        public virtual TipoRelacionParticipante TipoRelacionParticipante { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
