//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESAN.Componentes.CoreEvaluacion.Models.General.EvaluacionMSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRelacionParticipante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoRelacionParticipante()
        {
            this.Participante = new HashSet<Participante>();
        }
    
        public int TipoRelacionId { get; set; }
        public string DescripcionTipoRelacion { get; set; }
        public string EstadoTipoRelacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participante> Participante { get; set; }
    }
}
